apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: front-end-virtualservice
spec:
  hosts:
    - front-end-sockshop.itzroks-120000nskq-d0gq0n-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-south.containers.appdomain.cloud
  gateways:
    - sockshop-wildcard-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: front-end.sockshop.svc.cluster.local
        subset: v1
      weight: 80
    - destination:
        port:
          number: 80
        host: front-end.sockshop.svc.cluster.local
        subset: v2
      weight: 20
